#!/usr/bin/env bash

# Set up autograder files

if cp /autograder/submission/*/*.py /autograder/submission/;
then
	cp /autograder/submission/*.py /autograder/source/
fi

cd /autograder/source

echo "running"
python3 run_tests.py
echo "Done"
